# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: portainer-mcp-enhanced

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: portainer-mcp
    main: ./cmd/portainer-mcp
    binary: portainer-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - tools.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "🔒 Security"
      regexp: '^.*?sec(\(.+\))?\!?:.+$'
      order: 2
    - title: "📦 Other"
      order: 999

release:
  github:
    owner: jmrplens
    name: portainer-mcp-enhanced
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## Portainer MCP Enhanced {{.Tag}}

    ### Installation

    **Go install:**
    ```bash
    go install github.com/portainer/portainer-mcp/cmd/portainer-mcp@{{.Tag}}
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/jmrplens/portainer-mcp-enhanced:{{.Tag}}
    ```

    **Manual download:** See assets below for your platform.
  footer: |
    **Full Changelog**: https://github.com/jmrplens/portainer-mcp-enhanced/compare/{{.PreviousTag}}...{{.Tag}}

# Homebrew tap — disabled (no personal tap available yet)
# brews:
#   - name: portainer-mcp-enhanced
#     repository:
#       owner: jmrplens
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     homepage: "https://github.com/jmrplens/portainer-mcp-enhanced"
#     description: "Enhanced MCP server for AI-powered Portainer container management"
#     license: "MIT"
#     install: |
#       bin.install "portainer-mcp"
#     skip_upload: auto

# Docker images via GHCR
dockers:
  - image_templates:
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/jmrplens/portainer-mcp-enhanced"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - tools.yaml

  - image_templates:
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/jmrplens/portainer-mcp-enhanced"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - tools.yaml

docker_manifests:
  - name_template: "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}"
    image_templates:
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-amd64"
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/jmrplens/portainer-mcp-enhanced:latest"
    image_templates:
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-amd64"
      - "ghcr.io/jmrplens/portainer-mcp-enhanced:{{ .Tag }}-arm64"
