FROM alpine:3.21 AS certs
RUN apk --no-cache add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY portainer-mcp /usr/local/bin/portainer-mcp
COPY tools.yaml /tools.yaml
ENTRYPOINT ["/usr/local/bin/portainer-mcp"]
